[build]
  command = "npm run build -- --configuration production"
  publish = "dist/interactive-map-project"

[build.environment]
  NODE_VERSION = "26"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
